Muzoteka/Controllers/HomeController.cs
using Muzoteka.App_Start;
using Muzoteka.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Muzoteka.Controllers
{
    public class HomeController : Controller
    {
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(new utwor());
        }

        [AllowAnonymous]
        public ActionResult Search()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult About()
        {
            ViewBag.Message = "O autorze";

            return View();
        }

        [AllowAnonymous]
        public ActionResult Contact()
        {
            ViewBag.Message = "Strona kontaktowa";
            return View();
        }

        [Authorize]
        public ActionResult Welcome()
        {
            ViewBag.Message = "Witaj w Muzoteka!";
            return View();
        }

        [AllowAnonymous]
        public ActionResult Unauthorized()
        {
            return View();
        }
    }
}

Muzoteka/Controllers/UtworsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Muzoteka.Models;
using Muzoteka.App_Start;

namespace Muzoteka.Controllers
{
    public class UtworsController : Controller
    {
        private muzotekaEntities db = new muzotekaEntities();

        [Authorize]
        public ActionResult Index()
        {
            var utwor = db.utwor.Include(u => u.album).Include(u => u.playlista).Include(u => u.wykonawca);
            return View(utwor.ToList());
        }

        [AllowAnonymous]
        public ActionResult SearchedTracks(string trackName)
        {
            if(trackName.Equals(string.Empty))
            {
                RedirectToAction("Index", "Home");
            }
            using (muzotekaEntities db = new muzotekaEntities())
            {                
                List<utwor> utwors = db.utwor.Where(t => t.nazwa.ToLower().Contains(trackName.ToLower())).Include(u => u.album).Include(u => u.playlista).Include(u => u.wykonawca).Take(10).ToList();
                return View(utwors);
            }


        }

        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            utwor utwor = db.utwor.Find(id);
            if (utwor == null)
            {
                return HttpNotFound();
            }
            return View(utwor);
        }

        // GET: Utwors/Create
        [AuthorizeRoles("ADMIN")]
        public ActionResult Create()
        {
            ViewBag.idalbum = new SelectList(db.album, "id", "nazwa");
            ViewBag.idplaylista = new SelectList(db.playlista, "id", "nazwa");
            ViewBag.idwyk = new SelectList(db.wykonawca, "id", "imie");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles("ADMIN")]
        public ActionResult Create([Bind(Include = "id,nazwa,gatunek,dlugosc,link,dddb,idalbum,idwyk,idplaylista")] utwor utwor)
        {
            if (ModelState.IsValid)
            {
                db.utwor.Add(utwor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idalbum = new SelectList(db.album, "id", "nazwa", utwor.idalbum);
            ViewBag.idplaylista = new SelectList(db.playlista, "id", "nazwa", utwor.idplaylista);
            ViewBag.idwyk = new SelectList(db.wykonawca, "id", "imie", utwor.idwyk);
            return View(utwor);
        }

        [AuthorizeRoles("ADMIN")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            utwor utwor = db.utwor.Find(id);
            if (utwor == null)
            {
                return HttpNotFound();
            }
            ViewBag.idalbum = new SelectList(db.album, "id", "nazwa", utwor.idalbum);
            ViewBag.idplaylista = new SelectList(db.playlista, "id", "nazwa", utwor.idplaylista);
            ViewBag.idwyk = new SelectList(db.wykonawca, "id", "pseudonim", utwor.idwyk);
            return View(utwor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles("ADMIN")]
        public ActionResult Edit([Bind(Include = "id,nazwa,gatunek,dlugosc,link,dddb,idalbum,idwyk,idplaylista")] utwor utwor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(utwor).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idalbum = new SelectList(db.album, "id", "nazwa", utwor.idalbum);
            ViewBag.idplaylista = new SelectList(db.playlista, "id", "nazwa", utwor.idplaylista);
            ViewBag.idwyk = new SelectList(db.wykonawca, "id", "imie", utwor.idwyk);
            return View(utwor);
        }

        [AuthorizeRoles("ADMIN")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            utwor utwor = db.utwor.Find(id);
            if (utwor == null)
            {
                return HttpNotFound();
            }
            return View(utwor);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles("ADMIN")]
        public ActionResult DeleteConfirmed(int id)
        {
            utwor utwor = db.utwor.Find(id);
            db.utwor.Remove(utwor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Muzoteka/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Message</h2>

<h3>Autor: Tomasz Huchro</h3>

Muzoteka/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Kontakt";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        <strong>Autor:</strong>   <p>Tomasz Huchro</p>
        <strong>Mail:</strong>   <a href="mailto:Support@example.com">tomasz.huchro@gmail.com</a><br />
    </address>
}

Muzoteka/Views/Home/Index.cshtml
@model Muzoteka.Models.utwor
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron  text-center" style="background: url(../../Content/nuty.jpg) no-repeat center; height: 450px; background-size: cover; padding: 100px 0px 100px 0px">
    <h1>Muzoteka</h1>
    <p class="lead">Najlepsza muzyka w jednym miejscu</p>
</div>

<div class="row text-center">
    <h3>Wyszukiwarka utworów</h3>
    <div>
        <div class="form-inline">
            @Html.AntiForgeryToken()
            <div>
                @using (Html.BeginForm("SearchedTracks", "Utwors"))
                {
                    <input class="form-control" type="text" name="trackName" />
                    <input class="btn btn-primary" type="submit" value="Wyszukaj"/>
                }
            </div>
        </div>
    </div>
</div>

Muzoteka/Views/Home/Unauthorized.cshtml
@{
    ViewBag.Title = "Unauthorized";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dostęp zabroniony!</h2>
<p>Nie masz praw by oglądać tę stronę.</p>

<div>
    @Html.ActionLink("Powrót do strony głównej", "Index", "Home")
</div>

Muzoteka/Views/Home/Welcome.cshtml
<h2>Witaj</h2>
<h2>Hej <b>@Context.User.Identity.Name</b>, witaj w Muzoteka!</h2> 
@Html.ActionLink("Powrót na główną stronę", "Index", "Home", new { }, new { @class = "btn btn-primary" })