Muzoteka/Models/utwor.cs
namespace Muzoteka.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class utwor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public utwor()
        {
            this.ocena_utwor = new HashSet<ocena_utwor>();
        }

        public int id { get; set; }
        [Required]
        [Display(Name = "Nazwa")]
        public string nazwa { get; set; }
        [Required]
        [Display(Name = "Gatunek")]
        public string gatunek { get; set; }
        [Display(Name = "Długość [s]")]
        public Nullable<int> dlugosc { get; set; }
        [Display(Name = "Link")]
        [Required]
        public string link { get; set; }
        public System.DateTime dddb { get; set; }
        [Display(Name = "Album")]
        [Required]
        public int idalbum { get; set; }
        [Required]
        [Display(Name = "Wykonawca")]
        public int idwyk { get; set; }
        [Display(Name = "Playlista")]
        public Nullable<int> idplaylista { get; set; }

        [Display(Name = "Album")]
        public virtual album album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Ocena")]
        public virtual ICollection<ocena_utwor> ocena_utwor { get; set; }
        [Display(Name = "Playlista")]
        public virtual playlista playlista { get; set; }
        [Display(Name = "Wykonawca")]
        public virtual wykonawca wykonawca { get; set; }
    }
}

Muzoteka/Controllers/PlaylistasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Muzoteka.Models;
using Muzoteka.ViewModel;

namespace Muzoteka.Controllers
{
    public class PlaylistasController : Controller
    {
        private muzotekaEntities db = new muzotekaEntities();

        [Authorize]
        public ActionResult Index()
        {
            var playlista = db.playlista.Where(p => p.uzytkownik.login.Equals(HttpContext.User.Identity.Name));
            return View(playlista.ToList());
        }

        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            playlista playlista = db.playlista.Find(id);
            if (playlista == null)
            {
                return HttpNotFound();
            }
            return View(playlista);
        }

        [Authorize]
        public ActionResult Create()
        {
            ViewBag.iduzytkownik = db.uzytkownik.Where(u => u.login.Equals(HttpContext.User.Identity.Name)).First().id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "id,nazwa,data_utworzenia,opis")] playlista playlista)
        {
            playlista.iduzytkownik = db.uzytkownik.Where(u => u.login.Equals(HttpContext.User.Identity.Name)).First().id;
            if (ModelState.IsValid)
            {
                playlista.data_utworzenia = DateTime.Now;
                db.playlista.Add(playlista);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.iduzytkownik = playlista.iduzytkownik;
            return View(playlista);
        }

        [Authorize]
        public ActionResult InsertUtwor(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PlaylistaUtworViewModel data = new PlaylistaUtworViewModel();

            utwor utwor = db.utwor.Where(u => u.id == id).First();
            var playlistas = db.playlista.Where(p => p.uzytkownik.login.Equals(HttpContext.User.Identity.Name)).ToList();

            data.utwor = utwor;
            data.playlistas = playlistas;
            data.chosenPlaylista = new playlista();

            HttpContext.Session.Add("utworId", utwor.id);

            var allPlaylistasList = db.playlista.Where(p => p.uzytkownik.login.Equals(HttpContext.User.Identity.Name)).ToList();
            data.AllPlaylistas = allPlaylistasList.Select(o => new SelectListItem
            {
                Text = o.nazwa,
                Value = o.id.ToString()
            });

            return View(data);
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult InsertUtwor(PlaylistaUtworViewModel data)
        {
            var utworId = HttpContext.Session["utworId"];
            var selectedPlaylistas = db.playlista.Where(m => data.SelectedPlaylistas.Contains(m.id)).ToList();
            var playlistaList = (ICollection<playlista>)selectedPlaylistas;
            playlista playlista = playlistaList.First();

            utwor utwor = db.utwor.Where(u => u.id == (int)utworId).First();

            playlista.utwor.Add(utwor);

            db.Entry(playlista).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index", "Utwors", new { });
        }

        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            playlista playlista = db.playlista.Find(id);
            if (playlista == null)
            {
                return HttpNotFound();
            }
            ViewBag.iduzytkownik = db.uzytkownik.Where(u => u.login.Equals(HttpContext.User.Identity.Name)).First().id;
            HttpContext.Session.Add("playlistaTime", playlista.data_utworzenia);
            return View(playlista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "id,nazwa,data_utworzenia,opis")] playlista playlista)
        {
            playlista.iduzytkownik = db.uzytkownik.Where(u => u.login.Equals(HttpContext.User.Identity.Name)).First().id;
            if (ModelState.IsValid)
            {
                playlista.data_utworzenia = (DateTime)HttpContext.Session["playlistaTime"];
                db.Entry(playlista).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.iduzytkownik = new SelectList(db.uzytkownik, "id", "login", playlista.iduzytkownik);
            return View(playlista);
        }

        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            playlista playlista = db.playlista.Find(id);
            if (playlista == null)
            {
                return HttpNotFound();
            }
            return View(playlista);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            playlista playlista = db.playlista.Where(p => p.id == id).Include(p => p.utwor).First();
            playlista.utwor = new HashSet<utwor>();
            db.Entry(playlista).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            db.playlista.Remove(playlista);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Muzoteka/Controllers/UtworsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Muzoteka.Models;
using Muzoteka.App_Start;

namespace Muzoteka.Controllers
{
    public class UtworsController : Controller
    {
        private muzotekaEntities db = new muzotekaEntities();

        [Authorize]
        public ActionResult Index()
        {
            var utwor = db.utwor.Include(u => u.album).Include(u => u.playlista).Include(u => u.wykonawca);
            return View(utwor.ToList());
        }

        [AllowAnonymous]
        public ActionResult SearchedTracks(string trackName)
        {
            if(trackName.Equals(string.Empty))
            {
                RedirectToAction("Index", "Home");
            }
            using (muzotekaEntities db = new muzotekaEntities())
            {                
                List<utwor> utwors = db.utwor.Where(t => t.nazwa.ToLower().Contains(trackName.ToLower())).Include(u => u.album).Include(u => u.playlista).Include(u => u.wykonawca).Take(10).ToList();
                return View(utwors);
            }


        }

        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            utwor utwor = db.utwor.Find(id);
            if (utwor == null)
            {
                return HttpNotFound();
            }
            return View(utwor);
        }

        // GET: Utwors/Create
        [AuthorizeRoles("ADMIN")]
        public ActionResult Create()
        {
            ViewBag.idalbum = new SelectList(db.album, "id", "nazwa");
            ViewBag.idplaylista = new SelectList(db.playlista, "id", "nazwa");
            ViewBag.idwyk = new SelectList(db.wykonawca, "id", "imie");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles("ADMIN")]
        public ActionResult Create([Bind(Include = "id,nazwa,gatunek,dlugosc,link,dddb,idalbum,idwyk,idplaylista")] utwor utwor)
        {
            if (ModelState.IsValid)
            {
                db.utwor.Add(utwor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idalbum = new SelectList(db.album, "id", "nazwa", utwor.idalbum);
            ViewBag.idplaylista = new SelectList(db.playlista, "id", "nazwa", utwor.idplaylista);
            ViewBag.idwyk = new SelectList(db.wykonawca, "id", "imie", utwor.idwyk);
            return View(utwor);
        }

        [AuthorizeRoles("ADMIN")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            utwor utwor = db.utwor.Find(id);
            if (utwor == null)
            {
                return HttpNotFound();
            }
            ViewBag.idalbum = new SelectList(db.album, "id", "nazwa", utwor.idalbum);
            ViewBag.idplaylista = new SelectList(db.playlista, "id", "nazwa", utwor.idplaylista);
            ViewBag.idwyk = new SelectList(db.wykonawca, "id", "pseudonim", utwor.idwyk);
            return View(utwor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles("ADMIN")]
        public ActionResult Edit([Bind(Include = "id,nazwa,gatunek,dlugosc,link,dddb,idalbum,idwyk,idplaylista")] utwor utwor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(utwor).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idalbum = new SelectList(db.album, "id", "nazwa", utwor.idalbum);
            ViewBag.idplaylista = new SelectList(db.playlista, "id", "nazwa", utwor.idplaylista);
            ViewBag.idwyk = new SelectList(db.wykonawca, "id", "imie", utwor.idwyk);
            return View(utwor);
        }

        [AuthorizeRoles("ADMIN")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            utwor utwor = db.utwor.Find(id);
            if (utwor == null)
            {
                return HttpNotFound();
            }
            return View(utwor);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles("ADMIN")]
        public ActionResult DeleteConfirmed(int id)
        {
            utwor utwor = db.utwor.Find(id);
            db.utwor.Remove(utwor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Muzoteka/Views/Utwors/Create.cshtml
@model Muzoteka.Models.utwor

@{
    ViewBag.Title = "Nowy utwór";
}

<h2>Nowy utwór</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gatunek, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gatunek, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gatunek, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dlugosc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dlugosc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dlugosc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.link, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.link, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.link, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idalbum, "Album", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idalbum", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idalbum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idwyk, "Wykonawca", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idwyk", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idwyk, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy utworów", "Index", new { }, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Muzoteka/Views/Utwors/Delete.cshtml
@model Muzoteka.Models.utwor

@{
    ViewBag.Title = "Usuń";
}

<h2>Usuń</h2>

<h3>Czy na pewno chcesz usunąć utwór @Model.nazwa</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gatunek)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gatunek)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dlugosc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dlugosc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.link)
        </dd>

        <dt>
            Album
        </dt>

        <dd>
            @Html.DisplayFor(model => model.album.nazwa)
        </dd>

        <dt>
            Wykonawca
        </dt>

        <dd>
            @Html.DisplayFor(model => model.wykonawca.pseudonim)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-danger" />
            @Html.ActionLink("Powrót do listy", "Index", new { }, new { @class = "btn btn-primary" })
        </div>
    }
</div>

Muzoteka/Views/Utwors/Details.cshtml
@model Muzoteka.Models.utwor

@{
    ViewBag.Title = "Szczegóły";
}

<h2>Szczegóły utworu</h2>

<div>
    <h4>@Model.nazwa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gatunek)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gatunek)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dlugosc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dlugosc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.link)
        </dd>

        <dt>
            Album
        </dt>

        <dd>
            @Html.DisplayFor(model => model.album.nazwa)
        </dd>

        <dt>
            Wykonawca
        </dt>

        <dd>
            @Html.DisplayFor(model => model.wykonawca.pseudonim)
        </dd>

    </dl>
</div>
<p>
    @if (Context.User.IsInRole("ADMIN"))
    {
        @Html.ActionLink("Edytuj  ", "Edit", new { id = Model.id }, new { @class = "btn btn-primary" })
    }
    @Html.ActionLink("Powrót do listy utworów", "Index", new { }, new { @class = "btn btn-primary" })
</p>

Muzoteka/Views/Utwors/Edit.cshtml
@model Muzoteka.Models.utwor

@{
    ViewBag.Title = "Edycja";
}

<h2>Edytuj utwór</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Model.nazwa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gatunek, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gatunek, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gatunek, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dlugosc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dlugosc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dlugosc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.link, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.link, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.link, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idalbum, "Album", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idalbum", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idalbum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idwyk, "Wykonawca", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idwyk", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idwyk, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aktualizuj" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index", new { }, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Muzoteka/Views/Utwors/Index.cshtml
@model IEnumerable<Muzoteka.Models.utwor>

@{
    ViewBag.Title = "Utwory";
}

<h2>Utwory</h2>

@if (Context.User.IsInRole("ADMIN"))
{
    <p>
        @Html.ActionLink("Dodaj nowy utwór", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nazwa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gatunek)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dlugosc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.link)
        </th>
        <th>
            Album
        </th>
        <th>
            Wykonawca
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nazwa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gatunek)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dlugosc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.link)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.album.nazwa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.wykonawca.pseudonim)
            </td>
            <td>
                @Html.ActionLink("Szczegóły", "Details", new { id = item.id }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Dodaj do playlisty", "InsertUtwor", "Playlistas", new { id = item.id }, new { @class = "btn btn-primary" })

                @if (Context.User.IsInRole("ADMIN"))
                {
                    @Html.ActionLink("Edytuj", "Edit", new { id = item.id }, new { @class = "btn btn-primary" })

                    @Html.ActionLink("  Usuń", "Delete", new { id = item.id }, new { @class = "btn btn-danger" })
                }
            </td>

        </tr>
    }

</table>

Muzoteka/Views/Utwors/SearchedTracks.cshtml
@model IEnumerable<Muzoteka.Models.utwor>

@{
    ViewBag.Title = "Wyszukane utwory";
}

<h2>Top 10 wyników</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nazwa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gatunek)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dlugosc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.link)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.album.nazwa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.wykonawca.pseudonim)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nazwa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gatunek)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dlugosc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.link)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.album.nazwa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.wykonawca.pseudonim)
            </td>
        </tr>
    }
</table>

@Html.ActionLink("Powrót na główną stronę", "Index", "Home" , new { }, new { @class = "btn btn-primary" })